with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  github.com/IlfGauhnith/ReactiveBridge/internal/queue:
    interfaces:
      Producer: {}